### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by wrzwicky** [dakk/qc64#1]
Very cool project! I always wanted to try something like this.

Line 103 apparently should use gosub instead of goto.
Also, there are duplicate line numbers, and some line numbers are out of order. 
I used CBM prg Studio and fixed the obvious problems, and it seems to run fine, though I have no way of knowing if it is correct.

**Comment by dakk** [comment]
That's right, thank you wrzwicky! I put numbers after I write the full source, so I missed something ;)
